name: Build default Project
run-name: ${{ github.actor }} is build the default project 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: arm-none-eabi-gcc
        uses: ryanwinter/arm-none-eabi-gcc@master
        with:
          release: '10-2021.10'
      - name: Build binary
        run:  ./build.sh
      - run: echo "This job's status is ${{ job.status }}."
